server:
  port: 8081

javamelody:
  enabled: true
  spring-monitoring-enabled: true
  init-parameters:
    log: true
    authorized-users: admin:core

spring:
  rabbitmq:
    host: 52.3.74.224
    password: password
    username: admin
    port: 5672
    virtual-host: /